export const GET_USER_BOOKINGS = 'BOOKINGHISTORYCONTAINER/GET_USER_BOOKINGS';
export const GET_USER_BOOKINGS_SUCCESS =
  'BOOKINGHISTORYCONTAINER/GET_USER_BOOKINGS_SUCCESS';
export const GET_USER_BOOKINGS_FAILURE =
  'BOOKINGHISTORYCONTAINER/GET_USER_BOOKINGS_FAILURE';

export const DELETE_BOOKING = 'BOOKINGHISTORYCONTAINER/DELETE_BOOKING';
export const DELETE_BOOKING_SUCCESS =
  'BOOKINGHISTORYCONTAINER/DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILURE =
  'BOOKINGHISTORYCONTAINER/DELETE_BOOKING_FAILURE';

export const SAVE_REVIEW = 'BOOKINGHISTORYCONTAINER/SAVE_REVIEW';
export const SAVE_REVIEW_SUCCESS =
  'BOOKINGHISTORYCONTAINER/SAVE_REVIEW_SUCCESS';
export const SAVE_REVIEW_FAILURE =
  'BOOKINGHISTORYCONTAINER/SAVE_REVIEW_FAILURE';

export const UPDATE_BOOKING = 'BOOKINGHISTORYCONTAINER/UPDATE_BOOKING';
export const UPDATE_BOOKING_SUCCESS =
  'BOOKINGHISTORYCONTAINER/UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE =
  'BOOKINGHISTORYCONTAINER/UPDATE_BOOKING_FAILURE';

export const BOOKING_STATUS_BOOKED = 0;
export const BOOKING_STATUS_STARTED = 1;
export const BOOKING_STATUS_ENDED = 2;
export const BOOKING_STATUS_PENDING = 3;
export const BOOKING_STATUS_REJECTED = 4;
