export const SAVE_STATIONS = 'MAPCONTAINER/SAVE_STATIONS';
export const SAVE_STATIONS_SUCCESS = 'MAPCONTAINER/SAVE_STATIONS_SUCCESS';
export const SAVE_STATIONS_FAILURE = 'MAPCONTAINER/SAVE_STATIONS_FAILURE';
export const GET_FAVOURITE_STATIONS = 'MAPCONTAINER/GET_FAVOURITE_STATIONS';
export const GET_FAVOURITE_STATIONS_SUCCESS =
  'MAPCONTAINER/GET_FAVOURITE_STATIONS_SUCCESS';
export const GET_FAVOURITE_STATIONS_FAILURE =
  'MAPCONTAINER/GET_FAVOURITE_STATIONS_FAILURE';

export const ADD_STATION_TO_FAVOURITES =
  'MAPCONTAINER/ADD_STATION_TO_FAVOURITES';
export const ADD_STATION_TO_FAVOURITES_SUCCESS =
  'MAPCONTAINER/ADD_STATION_TO_FAVOURITES_SUCCESS';
export const ADD_STATION_TO_FAVOURITES_FAILURE =
  'MAPCONTAINER/ADD_STATION_TO_FAVOURITES_FAILURE';

export const DELETE_FAVOURITE_STATION = 'MAPCONTAINER/DELETE_FAVOURITE_STATION';
export const DELETE_FAVOURITE_STATION_SUCCESS =
  'MAPCONTAINER/DELETE_FAVOURITE_STATION_SUCCESS';
export const DELETE_FAVOURITE_STATION_FAILURE =
  'MAPCONTAINER/DELETE_FAVOURITE_STATION_FAILURE';
