export const SAVE_STATIONS = 'MAPCONTAINER/SAVE_STATIONS';
export const SAVE_STATIONS_SUCCESS = 'MAPCONTAINER/SAVE_STATIONS_SUCCESS';
export const SAVE_STATIONS_FAILURE = 'MAPCONTAINER/SAVE_STATIONS_FAILURE';
export const GET_FAVOURITE_STATIONS_INDEX =
  'MAPCONTAINER/GET_FAVOURITE_STATIONS_INDEX';
export const GET_FAVOURITE_STATIONS_INDEX_SUCCESS =
  'MAPCONTAINER/GET_FAVOURITE_STATIONS_INDEX_SUCCESS';
export const GET_FAVOURITE_STATIONS_INDEX_FAILURE =
  'MAPCONTAINER/GET_FAVOURITE_STATIONS_INDEX_FAILURE';

export const ADD_STATION_TO_FAVOURITES =
  'MAPCONTAINER/ADD_STATION_TO_FAVOURITES';
export const ADD_STATION_TO_FAVOURITES_SUCCESS =
  'MAPCONTAINER/ADD_STATION_TO_FAVOURITES_SUCCESS';
export const ADD_STATION_TO_FAVOURITES_FAILURE =
  'MAPCONTAINER/ADD_STATION_TO_FAVOURITES_FAILURE';

export const DELETE_FAVOURITE_STATION = 'MAPCONTAINER/DELETE_FAVOURITE_STATION';
export const DELETE_FAVOURITE_STATION_SUCCESS =
  'MAPCONTAINER/DELETE_FAVOURITE_STATION_SUCCESS';
export const DELETE_FAVOURITE_STATION_FAILURE =
  'MAPCONTAINER/DELETE_FAVOURITE_STATION_FAILURE';

// export const SAVE_PLUG = 'MAPCONTAINER/SAVE_PLUG';
// export const SAVE_PLUG_SUCCESS = 'MAPCONTAINER/SAVE_PLUG_SUCCESS';
// export const SAVE_PLUG_FAILURE = 'MAPCONTAINER/SAVE_PLUG_FAILURE';

export const GET_PLUGS = 'MAPCONTAINER/GET_PLUGS';
export const GET_PLUGS_SUCCESS = 'MAPCONTAINER/GET_PLUGS_SUCCESS';
export const GET_PLUGS_FAILURE = 'MAPCONTAINER/GET_PLUGS_FAILURE';

export const GET_REVIEWS = 'MAPCONTAINER/GET_REVIEWS';
export const GET_REVIEWS_SUCCESS = 'MAPCONTAINER/GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'MAPCONTAINER/GET_REVIEWS_FAILURE';
