export const GET_FAV_PUBLIC_STATIONS = 'MAPCONTAINER/GET_FAV_PUBLIC_STATIONS';
export const GET_FAV_PUBLIC_STATIONS_SUCCESS = 'MAPCONTAINER/GET_FAV_PUBLIC_STATIONS_SUCCESS';
export const GET_FAV_PUBLIC_STATIONS_FAILURE = 'MAPCONTAINER/GET_FAV_PUBLIC_STATIONS_FAILURE';
