export const UPDATE_USER = 'PROFILECONTAINER/UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'PROFILECONTAINER/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'PROFILECONTAINER/UPDATE_USER_FAILURE';

export const GET_USER = 'PROFILECONTAINER/GET_USER';
export const GET_USER_SUCCESS = 'PROFILECONTAINER/GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'PROFILECONTAINER/GET_USER_FAILURE';
