
export const GET_USER_CARS = 'HOMEPAGECONTAINER/GET_USER_CARS';
export const GET_USER_CARS_SUCCESS = 'HOMEPAGECONTAINER/GET_USER_CARS_SUCCESS';
export const GET_USER_CARS_FAILURE = 'HOMEPAGECONTAINER/GET_USER_CARS_FAILURE';
