export const GET_USER_CARS = 'HOMEPAGECONTAINER/GET_USER_CARS';
export const GET_USER_CARS_SUCCESS = 'HOMEPAGECONTAINER/GET_USER_CARS_SUCCESS';
export const GET_USER_CARS_FAILURE = 'HOMEPAGECONTAINER/GET_USER_CARS_FAILURE';

export const ADD_CAR = 'HOMEPAGECONTAINER/ADD_CAR';
export const ADD_CAR_SUCCESS = 'HOMEPAGECONTAINER/ADD_CAR_SUCCESS';
export const ADD_CAR_FAILURE = 'HOMEPAGECONTAINER/ADD_CAR_FAILURE';

export const DELETE_CAR = 'HOMEPAGECONTAINER/DELETE_CAR';
export const DELETE_CAR_SUCCESS = 'HOMEPAGECONTAINER/DELETE_CAR_SUCCESS';
export const DELETE_CAR_FAILURE = 'HOMEPAGECONTAINER/DELETE_CAR_FAILURE';

export const UPDATE_CAR = 'HOMEPAGECONTAINER/UPDATE_CAR';
export const UPDATE_CAR_SUCCESS = 'HOMEPAGECONTAINER/UPDATE_CAR_SUCCESS';
export const UPDATE_CAR_FAILURE = 'HOMEPAGECONTAINER/UPDATE_CAR_FAILURE';

export const GET_PLUGS = 'HOMEPAGECONTAINER/GET_PLUGS';
export const GET_PLUGS_SUCCESS = 'HOMEPAGECONTAINER/GET_PLUGS_SUCCESS';
export const GET_PLUGS_FAILURE = 'HOMEPAGECONTAINER/GET_PLUGS_FAILURE';

export const GET_STATIONS = 'HOMEPAGECONTAINER/GET_STATIONS';
export const GET_STATIONS_SUCCESS = 'HOMEPAGECONTAINER/GET_STATIONS_SUCCESS';
export const GET_STATIONS_FAILURE = 'HOMEPAGECONTAINER/GET_STATIONS_FAILURE';
