export const GET_USER_BOOKINGS = 'ACTIVEBOOKINGSCONTAINER/GET_USER_BOOKINGS';
export const GET_USER_BOOKINGS_SUCCESS =
  'ACTIVEBOOKINGSCONTAINER/GET_USER_BOOKINGS_SUCCESS';
export const GET_USER_BOOKINGS_FAILURE =
  'ACTIVEBOOKINGSCONTAINER/GET_USER_BOOKINGS_FAILURE';

export const DELETE_BOOKING = 'ACTIVEBOOKINGSCONTAINER/DELETE_BOOKING';
export const DELETE_BOOKING_SUCCESS =
  'ACTIVEBOOKINGSCONTAINER/DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILURE =
  'ACTIVEBOOKINGSCONTAINER/DELETE_BOOKING_FAILURE';

export const GET_CONTRIBUTOR_BOOKINGS =
  'ACTIVEBOOKINGSCONTAINER/GET_CONTRIBUTOR_BOOKINGS';
export const GET_CONTRIBUTOR_BOOKINGS_SUCCESS =
  'ACTIVEBOOKINGSCONTAINER/GET_CONTRIBUTOR_BOOKINGS_SUCCESS';
export const GET_CONTRIBUTOR_BOOKINGS_FAILURE =
  'ACTIVEBOOKINGSCONTAINER/GET_CONTRIBUTOR_BOOKINGS_FAILURE';

export const UPDATE_BOOKING_STATUS =
  'ACTIVEBOOKINGSCONTAINER/UPDATE_BOOKING_STATUS';
export const UPDATE_BOOKING_SUCCESS_STATUS =
  'ACTIVEBOOKINGSCONTAINER/UPDATE_BOOKING_SUCCESS_STATUS';
export const UPDATE_BOOKING_FAILURE_STATUS =
  'ACTIVEBOOKINGSCONTAINER/UPDATE_BOOKING_FAILURE_STATUS';

export const BOOKING_STATUS_ACTIVE = 0;
export const BOOKING_STATUS_STARTED = 1;
export const BOOKING_STATUS_ENDED = 2;
export const BOOKING_STATUS_PENDING = 3;
export const BOOKING_STATUS_REJECTED = 4;
