export const GET_FAVOURITE_STATIONS =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS';
export const GET_FAVOURITE_STATIONS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS_SUCCESS';
export const GET_FAVOURITE_STATIONS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS_FAILURE';
