export const GET_FAVOURITE_STATIONS =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS';
export const GET_FAVOURITE_STATIONS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS_SUCCESS';
export const GET_FAVOURITE_STATIONS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS_FAILURE';

export const GET_PLUGS = 'FAVOURITESTATIONSCONTAINER/GET_PLUGS';
export const GET_PLUGS_SUCCESS = 'FAVOURITESTATIONSCONTAINER/GET_PLUGS_SUCCESS';
export const GET_PLUGS_FAILURE = 'FAVOURITESTATIONSCONTAINER/GET_PLUGS_FAILURE';

export const GET_REVIEWS = 'FAVOURITESTATIONSCONTAINER/GET_REVIEWS';
export const GET_REVIEWS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_REVIEWS_FAILURE';

export const GET_USER_CARS = 'FAVOURITESTATIONSCONTAINER/GET_USER_CARS';
export const GET_USER_CARS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_USER_CARS_SUCCESS';
export const GET_USER_CARS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_USER_CARS_FAILURE';

export const ADD_STATION = 'FAVOURITESTATIONSCONTAINER/ADD_STATION';
export const ADD_STATION_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/ADD_STATION_SUCCESS';
export const ADD_STATION_FAILURE =
  'FAVOURITESTATIONSCONTAINER/ADD_STATION_FAILURE';

export const GET_USER_STATIONS = 'FAVOURITESTATIONSCONTAINER/GET_USER_STATIONS';
export const GET_USER_STATIONS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_USER_STATIONS_SUCCESS';
export const GET_USER_STATIONS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_USER_STATIONS_FAILURE';

export const DELETE_STATION = 'FAVOURITESTATIONSCONTAINER/DELETE_STATION';
export const DELETE_STATION_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/DELETE_STATION_SUCCESS';
export const DELETE_STATION_FAILURE =
  'FAVOURITESTATIONSCONTAINER/DELETE_STATION_FAILURE';

export const SAVE_BOOKING = 'FAVOURITESTATIONSCONTAINER/SAVE_BOOKING';
export const SAVE_BOOKING_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/SAVE_BOOKING_SUCCESS';
export const SAVE_BOOKING_FAILURE =
  'FAVOURITESTATIONSCONTAINER/SAVE_BOOKING_FAILURE';

export const VERIFY_BOOKING = 'FAVOURITESTATIONSCONTAINER/VERIFY_BOOKING';
export const VERIFY_BOOKING_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/VERIFY_BOOKING_SUCCESS';
export const VERIFY_BOOKING_FAILURE =
  'FAVOURITESTATIONSCONTAINER/VERIFY_BOOKING_FAILURE';

export const GET_PLUGS_AFTER_CAR_TYPE =
  'FAVOURITESTATIONSCONTAINER/GET_PLUGS_AFTER_CAR_TYPE';
export const GET_PLUGS_AFTER_CAR_TYPE_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_PLUGS_AFTER_CAR_TYPE_SUCCESS';
export const GET_PLUGS_AFTER_CAR_TYPE_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_PLUGS_AFTER_CAR_TYPE_FAILURE';

export const GET_PLUGS_AFTER_CAR_TYPE_QUIET =
  'FAVOURITESTATIONSCONTAINER/GET_PLUGS_AFTER_CAR_TYPE_QUIET';

export const CLOSE_ALERTS = 'FAVOURITESTATIONSCONTAINER/CLOSE_ALERTS';

export const CLEAR_ADD_STATION_ERROR =
  'FAVOURITESTATIONSCONTAINER/CLEAR_ADD_STATION_ERROR';
