export const GET_FAVOURITE_STATIONS =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS';
export const GET_FAVOURITE_STATIONS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS_SUCCESS';
export const GET_FAVOURITE_STATIONS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_FAVOURITE_STATIONS_FAILURE';

export const GET_PLUGS = 'FAVOURITESTATIONSCONTAINER/GET_PLUGS';
export const GET_PLUGS_SUCCESS = 'FAVOURITESTATIONSCONTAINER/GET_PLUGS_SUCCESS';
export const GET_PLUGS_FAILURE = 'FAVOURITESTATIONSCONTAINER/GET_PLUGS_FAILURE';

export const GET_REVIEWS = 'FAVOURITESTATIONSCONTAINER/GET_REVIEWS';
export const GET_REVIEWS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_REVIEWS_FAILURE';

export const GET_USER_CARS = 'FAVOURITESTATIONSCONTAINER/GET_USER_CARS';
export const GET_USER_CARS_SUCCESS =
  'FAVOURITESTATIONSCONTAINER/GET_USER_CARS_SUCCESS';
export const GET_USER_CARS_FAILURE =
  'FAVOURITESTATIONSCONTAINER/GET_USER_CARS_FAILURE';
